name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: Run misspell with reviewdog
        uses: reviewdog/action-misspell@v1.12.3
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
